apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: optimus
  template:
    metadata:
      labels:
        name: optimus
    spec:
      serviceAccountName: optimus
      containers:
        - name: optimus
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - optimus
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "optimus"
