kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: optimus
subjects:
- kind: ServiceAccount
  name: optimus
roleRef:
  kind: Role
  name: optimus
  apiGroup: rbac.authorization.k8s.io
