apiVersion: v1
kind: Namespace
metadata:
  name: ci-namespace
---
apiVersion: cloudflavor/v1
kind: Pipeline
metadata:
  name: pipelines
  labels:
    app: test
  namespace: ci-namespace
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pipelines
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelines
        env: dev # NOTE: see how to configure this.
    spec:
      containers:
      - name: pipelines
        image: quay.io/cloudflavor/pipelines
        imagePullPolicy: Always
