apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.hooks.cloudflavor.io
spec:
  group: hooks.cloudflavor.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: deployments
    singular: deployment
    kind: Deployment
    shortNames:
    - dh
