apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ci.pipelines.cloudflavor.io
spec:
  group: pipelines.cloudflavor.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: CIPipelines
    shortNames:
    - cpr
