---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.optimus.cloudflavor.io
spec:
  version: v1
  group: optimus.cloudflavor.io
  scope: Namespaced
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
    shortNames:
    - pipe
