---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimus-cr
  labels:
    app: optimus
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - optimus.cloudflavor.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimus-sa
  namespace: optimus
  labels:
    app: optimus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimus-crb
  labels:
    app: optimus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: optimus-cr
subjects:
- kind: ServiceAccount
  name: optimus-sa
  namespace: optimus