---
apiVersion: v1
kind: Namespace
metadata:
  name: optimus
---
apiVersion: optimus.cloudflavor.io/v1
kind: Pipeline
metadata:
  name: pipelines
  namespace: optimus
  labels:
    app: pipelines
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pipelines
  namespace: optimus
  labels:
    app: pipelines
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      containers:
      - name: pipelines
        image: quay.io/cloudflavor/optimus:latest
        imagePullPolicy: Always
      serviceAccountName: pipelines